import = [ "~/.config/alacritty/themes/themes/nord.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
opacity = 0.95
decorations = "full"

[font]
size = 9

  [font.normal]
  family = "RobotoMono Nerd Font"
  style = "regular"
  [font.bold]
  family = "RobotoMono Nerd Font"
  style = "bold"
  [font.italic]
  family = "RobotoMono Nerd Font"
  style = "italic"
  [font.bold_italic]
  family = "RobotoMono Nerd Font"
  style = "bold-italic"
